### ISSUE TITLE
Installer Error

### ISSUE THREAD

**Issue by AhrimanSefid** [nicholasryan/CorePlus#3]
( ! ) Notice: Requested config file configuration.xml not located within C:\wamp\www\Co/config/ in C:\wamp\www\Co\core\bootstrap.compiled.php on line 13629
Call Stack
#	Time	Memory	Function	Location
1	0.0023	142744	{main}( )	..\index.php:0
2	0.1038	4410232	require_once( 'C:\wamp\www\Co\core\bootstrap.compiled.php' )	..\index.php:35
3	0.1083	4605608	ConfigHandler::LoadConfigFile( )	..\bootstrap.compiled.php:13789
4	0.1083	4605784	ConfigHandler->_loadConfigFile( )	..\bootstrap.compiled.php:13717
5	0.1086	4606136	trigger_error ( )	..\bootstrap.compiled.php:13629
Please install Core Plus.

(You may need to refresh this page a time or two if you just installed)

**Comment by nicholasryan** [comment]
"Requested config file configuration.xml not located within..." is an error message you are getting because the repository version of Core Plus has the compiled version of the bootstrap file, which expects src/config/configuration.xml to exist.

Copy configuration.example.xml to configuration.xml, then modify the database settings in the file to reflect your local environment.

**Comment by cdp1337** [comment]
It seems that the system just isn't installed and you have full messages enabled, (which is a good thing).  Just append /install to your URL and try the installer.
